### ISSUE TITLE
Write design document for the Fission Server

### ISSUE THREAD

**Issue by bdehaynin** [fission-codes/fission-server#151]
The design document should be a blueprint that explains in details what the Fission Server is, and how we will build it. 
It needs to capture and reflect the agreements and decisions coming from discussions that in Talk.

We can add a glossary as well to make sure everyone knows what we mean when using specific terms. 

If you're ok with it, add it in this repository so that it lives in the same place as the code.

**Comment by matheus23** [comment]
Some work on this by @expede: https://github.com/fission-codes/fission-server/blob/design-doc/design/README.md

**Comment by expede** [comment]
> We can add a glossary as well to make sure everyone knows what we mean when using specific terms.

I broke out a table at one point, but the main `design/README.md` is kind of like an expanded version of that, so cut it.

> Merge or add a link to the open API spec

Has to wait for the code to be done. I'd suggest breaking this out as a separate Issue to keep things flowing. Arguably it's conceptually a separate step: prescriptive (pre hoc) vs descriptive (post hoc)
