### ISSUE TITLE
Subaccount creation REST API

### ISSUE THREAD

**Issue by expede** [fission-codes/fission-server#181]
[Tech Deisgn Docs 📜](https://github.com/fission-codes/fission-server/blob/design-doc/design/README.md#api-endpoints)

|REST Action | HTTP Verb | Path |
| -- | -- | -- |
| Create | `POST` | `/v0/api/account/:id/sub` |

ETA: 2023-10-07

**Comment by matheus23** [comment]
Will close this as "not planned" for now.
