### ISSUE TITLE
UCAN Revocations

### ISSUE THREAD

**Issue by expede** [fission-codes/fission-server#185]
The Fission Sever should support [UCAN Revocations](https://github.com/ucan-wg/revocation/) (at time of writing, the [1.0 PR](https://github.com/ucan-wg/revocation/pull/1) is in progress).

This requires three steps:

1. Persisting revocations to the DB
2. Deleting (or at least marking invalid) any associated UCAN in the capability store
3. Checking if a UCAN matches the revocation list on validation of any new UCAN

As usual, see the tech design docs for a proposed schema.

ETA: 2023-10-31

**Comment by matheus23** [comment]
Closed in #201
