### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by icidasset** [fission-codes/fission-server#58]
Need to support two types of accounts
- [x] Developer accounts (same shape of current implementation)
- [ ] App accounts (tied to specific app, special subdomain scoped per app, [context](https://talk.fission.codes/t/app-accounts-usernames-and-file-root-stores/4494))

As opposed to previous implementation, an account's identity is not necessarily a did:key. We'll use a generic did field instead of putting the resolved did:key bytes into the DB.

Dev account info:  did + email
App account info: did

We also need a name for the fission subdomain, this'll be the username.

**Comment by matheus23** [comment]
Closing this - we're not doing app accounts in the near future.
